import type { NextPage } from 'next';
import React, { useEffect, useMemo, useState } from 'react';
import Head from 'next/head';

import Table from '../components/Table';

const Home: NextPage = () => {

  const [weight, setWeight] = useState<number>();

  const [data, setData] = useState([]);
  
  const columns = useMemo(
    () => [
      {
        Header: 'Percentage',
        accessor: 'percentage', // accessor is the "key" in the data
      },
      {
        Header: 'Weight',
        accessor: 'weight',
      },
    ],
    []
  );

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1 className="text-3xl font-bold underline text-gray-400">
          Hello world! Weight is {weight}
        </h1>

        <input type="number" value={weight} onChange={(evt) => setWeight(Number(evt.target.value))}/>
        <Table columns={columns} data={data} />
      </main>
      <footer>
      </footer>
    </div>
  );
};

export default Home;